# Exported from Render on 2026-04-19T11:29:40Z
version: "1"
projects:
- name: My project
  environments:
  - name: DAVSlm
    services:
    - type: web
      name: DAVSlm
      runtime: python
      repo: https://github.com/cptleftnut/DavsAI
      plan: free
      envVars:
      - key: GROQ_API_KEY
        sync: false
      region: oregon
      buildCommand: pip install -r requirements.txt
      startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
      autoDeployTrigger: commit
      rootDir: backend
      previews:
        generation: automatic
