name: Byg DAVSlm Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Hent kildekode
        uses: actions/checkout@v3

      - name: Opsæt Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Opsæt Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # Låst til 17 for stabilitet

      - name: Installer afhængigheder
        run: npm install --verbose

      - name: TRO PÅ DET DAV! OG PRØV SÅ IGEN!
        working-directory: android
        run: ./gradlew assembleRelease

      - name: Gem APK filen
        uses: actions/upload-artifact@v3
        with:
          name: DAVSlm-APK
          path: android/app/build/outputs/apk/release/app-release.apk
